GRADIENT_BREAKPOINT = "gradient"
MODEL_DIMENSION = 3072

MIN_POOL_SIZE = 20
MAX_POOL_SIZE = 40
MAX_CONCURRENT_PROVISIONER = 10

TIME_THRESHOLD = 12

HNSW_EF = 10
SPARSE_DROP_RATIO = 0.2
RERANKER_SMOOTHING_PARAMETERS = 60