"""added status column to knowledge_base_documents

Revision ID: e220acbdf8e2
Revises: b0026fe4df1c
Create Date: 2025-06-28 13:29:21.581271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e220acbdf8e2'
down_revision: Union[str, None] = 'b0026fe4df1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base_documents', sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='operation_status'), server_default='PENDING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_base_documents', 'status')
    # ### end Alembic commands ###
