// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_client.sql

package database

import (
	"context"
)

const registerUser = `-- name: RegisterUser :one
insert into user_clients (
    email
) values (
    $1
) returning id, email, created_at, updated_at
`

func (q *Queries) RegisterUser(ctx context.Context, email string) (UserClient, error) {
	row := q.db.QueryRow(ctx, registerUser, email)
	var i UserClient
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
