// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: knowledge_base_document.sql

package database

import (
	"context"
)

const createKnowledgeBaseDocuments = `-- name: CreateKnowledgeBaseDocuments :one
insert into knowledge_base_documents(
    ingestion_id,
    knowledge_base_id,
    document_id
) values (
    $1, $2, $3
) returning id, ingestion_id, knowledge_base_id, document_id, created_at, updated_at
`

type CreateKnowledgeBaseDocumentsParams struct {
	IngestionID     int32 `json:"ingestion_id"`
	KnowledgeBaseID int32 `json:"knowledge_base_id"`
	DocumentID      int32 `json:"document_id"`
}

func (q *Queries) CreateKnowledgeBaseDocuments(ctx context.Context, arg CreateKnowledgeBaseDocumentsParams) (KnowledgeBaseDocument, error) {
	row := q.db.QueryRow(ctx, createKnowledgeBaseDocuments, arg.IngestionID, arg.KnowledgeBaseID, arg.DocumentID)
	var i KnowledgeBaseDocument
	err := row.Scan(
		&i.ID,
		&i.IngestionID,
		&i.KnowledgeBaseID,
		&i.DocumentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
