// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: knowledge_base.sql

package database

import (
	"context"
)

const createKnowledgeBase = `-- name: CreateKnowledgeBase :one
insert into knowledge_bases (
    user_id,
    name
) values (
    $1, $2
) returning id, user_id, name, created_at, updated_at
`

type CreateKnowledgeBaseParams struct {
	UserID int32  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateKnowledgeBase(ctx context.Context, arg CreateKnowledgeBaseParams) (KnowledgeBasis, error) {
	row := q.db.QueryRow(ctx, createKnowledgeBase, arg.UserID, arg.Name)
	var i KnowledgeBasis
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKnowledgeBase = `-- name: DeleteKnowledgeBase :exec
delete from knowledge_bases
where name = $1
`

func (q *Queries) DeleteKnowledgeBase(ctx context.Context, knowledgeBaseName string) error {
	_, err := q.db.Exec(ctx, deleteKnowledgeBase, knowledgeBaseName)
	return err
}
